name: cloudbase_function
description: Flutter plugin for cloudbase function.
version: 0.0.1
homepage: https://github.com/TencentCloudBase

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloudbase_core: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
