name: cloudbase_storage
description: Flutter plugin for cloudbase storage.
version: 0.0.2
homepage: https://github.com/TencentCloudBase

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloudbase_core: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^1.5.1

